- hosts: k3s_master
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Check if K3s is already installed on master
      stat:
        path: /etc/rancher/k3s
      register: k3s_installed_master

    - name: Install K3s on master if not already installed
      shell: curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_cluster_token }} K3S_VERSION={{ k3s_version }} INSTALL_K3S_EXEC="--cluster-init" sh -
      when: k3s_installed_master.stat.exists == False

    - name: Get Kubeconfig file if necessary
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./k3s.yaml
        flat: yes
      when: k3s_installed_master.stat.exists == False

- hosts: k3s_nodes
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Check if K3s is already installed on workers
      stat:
        path: /etc/rancher/k3s
      register: k3s_installed_workers

    - name: Install K3s on workers if not already installed
      shell: curl -sfL https://get.k3s.io | K3S_URL={{ k3s_url }} K3S_TOKEN={{ k3s_cluster_token }} K3S_VERSION={{ k3s_version }} sh -
      when: k3s_installed_workers.stat.exists == False

- hosts: localhost
  tasks:
    - name: Modify k3s.yaml file
      replace:
        path: ./k3s.yaml
        regexp: 'server: https://127\.0\.0\.1:6443'
        replace: 'server: https://10.105.100.56:6443'
